# Guest OS timezone
timezone: Europe/Moscow

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: microservice

# Virtual machine IP
ip: 192.168.83.137

# Virtual machine CPU cores number
cpus: 2

# Virtual machine RAM
memory: 1536
